name: Github action demo
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ğŸš€ first 
      - run: echo ğŸ˜ cool
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ğŸ’ğŸ½

# name: Github action demo
# on: [push]
# jobs:
#   Explore-Github-Actins:
#     runs-on: ubuntu-latest
#     steps: 
#       - run: echo "this is the first"
#       - run: echo "ğŸ˜— second ğŸ˜œ"
#       - name: checkout code
#         uses: actions/checkout@v3
#       - run: echo "The repo ${{ github.repository }} has been cloned"
#       - name: List files in repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "The job status ${{ job.status }}"
    